---
- hosts: 127.0.0.1
  #vars_prompt:
  #  - name: src_directory
  #    prompt: "Enter path to your openshift-ansible"
  #    private: no
  #  - name: dst_directory
  #    prompt: "Enter path to place openshift-ansible-contrail"
  #    private: no
  tasks:
    - name: pull the latest openshift-contrail-code from git
      git:
       repo: https://github.com/Juniper/openshift-ansible.git
       dest: "{{ dst_directory }}"
       version: release-3.9-contrail

    - name: copy contrail_master into your openshift-ansible-deployer
      command: cp -r {{dst_directory}}/roles/contrail_master {{src_directory}}/roles/.
    - name: copy contrail_nodes folder into your openshift-ansible-deployer
      command: cp -r {{dst_directory}}/roles/contrail_node {{src_directory}}/roles/.

    - name: "Set permissions for replacement master config files"
      file: path=/home/custom-openshift/ose/files/replace.sh mode=0777
    - name: "Execute the script"
      script: /home/custom-openshift/ose/files/replace.sh

    - name: "Set permissions for replacement node config files"
      file: path=/home/custom-openshift/ose/files/modify.sh mode=0777
    - name: "Execute the script"
      script: /home/custom-openshift/ose/files/modify.sh
     
    - name: "Set permissions for replacement node config files"
      file: path=/home/custom-openshift/ose/files/append_nodes.sh mode=0777
    - name: "Execute the script"
      script: /home/custom-openshift/ose/files/append_nodes.sh

    - name: "Set permissions for replacement contrail config files"
      file: path=/home/custom-openshift/ose/files/copy_config.sh mode=0777
    - name: "Execute the script"
      script: /home/custom-openshift/ose/files/copy_config.sh
